-- ============================================================
-- Reunion planning: real event dates + Budget Estimator +
-- Timeline Builder
-- ============================================================

-- ---- reunions: real dates (year is kept for backward compat) ----
alter table reunions
  add column if not exists start_date date,
  add column if not exists end_date date;

-- ---- reunion_budget_estimates ----
-- One row per reunion holding the Budget Estimator inputs + a cached total.
create table reunion_budget_estimates (
  id uuid primary key default uuid_generate_v4(),
  reunion_id uuid not null unique references reunions(id) on delete cascade,
  host_city text,
  nights integer not null default 1 check (nights >= 1),
  budget_style text not null default 'average' check (budget_style in ('low', 'average', 'high')),
  adults_count integer not null default 0 check (adults_count >= 0),
  youth_count integer not null default 0 check (youth_count >= 0),
  toddlers_count integer not null default 0 check (toddlers_count >= 0),
  lodging_type text not null default 'hotel_resort',
  categories jsonb not null default '[]',
  total_estimate numeric(10, 2) not null default 0,
  created_by uuid references members(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger reunion_budget_estimates_updated_at
  before update on reunion_budget_estimates
  for each row execute function handle_updated_at();

-- ---- reunion_timeline_items ----
-- Individual checklist rows generated by the Timeline Builder (or added by
-- hand). Real rows (not JSON) so each item can be checked off independently
-- and shared across the whole committee.
create table reunion_timeline_items (
  id uuid primary key default uuid_generate_v4(),
  reunion_id uuid not null references reunions(id) on delete cascade,
  title text not null,
  phase_label text,
  category text not null default 'logistics' check (
    category in ('logistics', 'venue', 'lodging', 'rsvp', 'vendor', 'merchandise', 'heritage', 'final')
  ),
  due_date date,
  is_complete boolean not null default false,
  is_custom boolean not null default false,
  sort_order integer not null default 0,
  created_by uuid references members(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger reunion_timeline_items_updated_at
  before update on reunion_timeline_items
  for each row execute function handle_updated_at();

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

alter table reunion_budget_estimates enable row level security;
alter table reunion_timeline_items enable row level security;

-- ---- reunion_budget_estimates ----
create policy "BudgetEstimates: authenticated users can view" on reunion_budget_estimates
  for select to authenticated using (true);

create policy "BudgetEstimates: committee/admin can create" on reunion_budget_estimates
  for insert to authenticated
  with check (get_my_role() in ('committee', 'admin'));

create policy "BudgetEstimates: committee/admin can update" on reunion_budget_estimates
  for update to authenticated
  using (get_my_role() in ('committee', 'admin'));

create policy "BudgetEstimates: committee/admin can delete" on reunion_budget_estimates
  for delete to authenticated
  using (get_my_role() in ('committee', 'admin'));

-- ---- reunion_timeline_items ----
create policy "TimelineItems: authenticated users can view" on reunion_timeline_items
  for select to authenticated using (true);

create policy "TimelineItems: committee/admin can create" on reunion_timeline_items
  for insert to authenticated
  with check (get_my_role() in ('committee', 'admin'));

-- Any authenticated member can check items off (shared family checklist),
-- not just committee/admin. The app only exposes toggling is_complete here;
-- editing title/due_date etc. is restricted to committee/admin at the app layer.
create policy "TimelineItems: any member can update" on reunion_timeline_items
  for update to authenticated using (true);

create policy "TimelineItems: committee/admin can delete" on reunion_timeline_items
  for delete to authenticated
  using (get_my_role() in ('committee', 'admin'));
